services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: trader
      POSTGRES_DB: trader
    volumes:
      - trader_pg:/var/lib/postgresql/data

volumes:
  trader_pg:
